name: Approved PR check

on:
  pull_request_review:
    types: 
      - submitted

jobs:
  get-version-string:
    name: Get version string
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set vars
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}

  build:
    name: Build
    if: github.event.review.state == 'APPROVED'
    uses: ./.github/workflows/build.yaml
    needs: get-version-string
    with:
      version: ${{ github.ref_name }}-${{ needs.get-version-string.outputs.short_sha }}
