name: Build pushes and pull requests

on:
  push:
    branches-ignore:
      - dev
    tags-ignore:
      - v*
  pull_request:

jobs:
  get-version-string:
    name: Get version string
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set vars
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}

  build-push:
    if: ${{ github.event_name == 'push' }}
    name: Build Push
    uses: ./.github/workflows/build.yaml
    needs: get-version-string
    with:
      version: ${{ github.ref_name }}-${{ needs.get-version-string.outputs.short_sha }}

  build-pr:
    if: ${{ github.event_name == 'pull_request' }}
    name: Build PR
    uses: ./.github/workflows/build.yaml
    needs: get-version-string
    with:
      version: pr-${{ github.ref_name }}-${{ needs.get-version-string.outputs.short_sha }}
